import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: 'Savrse Help Center',
  tagline: 'Documentation and Tutorial',
  favicon: 'img/favicon.png',

  future: {
    v4: true,
  },

  url: 'http://savrse.savameta.local:3000',
  baseUrl: '/help/',
  organizationName: 'facebook',
  projectName: 'docusaurus',
  onBrokenLinks: 'warn',
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'vi'],
    localeConfigs: {
      en: { label: 'English' },
      vi: { label: 'Tiếng Việt' },
    },
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.autogenerated.js',
          // editUrl:
          //   'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/',
          showLastUpdateAuthor: false,
          showLastUpdateTime: false,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: ['./plugins/custom-doc-routes.js'],

  themeConfig: {
    image: 'img/docusaurus-social-card.jpg',
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: '',
      logo: {
        alt: 'SAVRSE LOGO',
        src: 'img/logo.svg',
        href: 'https://savrse.savameta.com',
      },
      items: [],
      // hideOnScroll: false,
    },
    footer: {
      style: 'dark',

      links: [
        {
          title: 'Community',
          items: [
            {
              label: 'About Us',
              href: 'https://savrse.savameta.com/about-us',
            },
            {
              label: 'Creator Hub',
              href: 'https://savrse.savameta.com/creator',
            },
            {
              label: 'World',
              href: 'https://savrse.savameta.com/world',
            },
            {
              label: 'Avatar',
              href: 'https://savrse.savameta.com/avatar',
            },
          ],
        },
        {
          title: 'Follow Us on',
          items: [
            {
              label: 'Facebook',
              href: 'https://www.facebook.com/savameta.tech',
            },
            {
              label: 'LinkedIn',
              href: 'https://www.linkedin.com/company/sava-meta',
            },
            {
              label: 'Tiktok',
              href: 'https://www.tiktok.com/@savameta.ontrend',
            },
            {
              label: 'Youtube',
              href: 'https://www.youtube.com/@savameta_2024',
            }
          ],
        },
      ],
      copyright: `Copyright © SAVRSE ${new Date().getFullYear()}. All rights reserved.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
