# Khi dùng baseUrl /help/, set SERVICE_PATH=/help để location trùng với base path.
server {

    server_name localhost;

    index index.html;

    root /usr/share/nginx/html;

    location /service_path {

        try_files $uri $uri/.html /service_path/index.html;

    }

}