/**
 * Đảm bảo luôn có docs hợp lệ trước khi chạy Docusaurus.
 * Nếu docs/ trống hoặc sidebars.autogenerated.js thiếu → tạo intro.md + sidebars/navbar tối thiểu.
 * Nội dung chính: thêm/sửa file .md trong thư mục docs/.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DOCS_DIR = path.join(ROOT, 'docs');
const SIDEBARS_PATH = path.join(ROOT, 'sidebars.autogenerated.js');
const NAVBAR_PATH = path.join(ROOT, 'navbar.autogenerated.js');

function hasAnyMd(dir) {
  if (!fs.existsSync(dir)) return false;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const e of entries) {
    if (e.isFile() && e.name.endsWith('.md')) return true;
    if (e.isDirectory()) {
      if (hasAnyMd(path.join(dir, e.name))) return true;
    }
  }
  return false;
}

function ensureDocs() {
  const needsFallback =
    !fs.existsSync(DOCS_DIR) ||
    !hasAnyMd(DOCS_DIR) ||
    !fs.existsSync(SIDEBARS_PATH);

  if (!needsFallback) {
    console.log('[ensure-docs] Docs and sidebars OK, skip.');
    return;
  }

  console.log('[ensure-docs] Creating minimal docs (intro) and sidebars...');

  if (!fs.existsSync(DOCS_DIR)) {
    fs.mkdirSync(DOCS_DIR, { recursive: true });
  }

  const introContent = `---
title: "Welcome"
---

# Welcome to Sava Meta Documentation

Add and edit content in the \`docs/\` folder.`;

  fs.writeFileSync(path.join(DOCS_DIR, 'intro.md'), introContent);

  const sidebarsContent = `// Fallback from ensure-docs.js when no docs were present.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: 'doc', id: 'intro' }]
};
module.exports = sidebars;
`;

  fs.writeFileSync(SIDEBARS_PATH, sidebarsContent);

  const navbarContent = `// Fallback from ensure-docs.js when no docs were present.
/** @type {import('@docusaurus/preset-classic').ThemeConfig['navbar']['items']} */
const navbarItems = [
  { type: 'doc', docId: 'intro', position: 'left', label: 'Docs' }
];
module.exports = navbarItems;
`;

  fs.writeFileSync(NAVBAR_PATH, navbarContent);

  console.log('[ensure-docs] Created docs/intro.md and fallback sidebars/navbar.');
}

ensureDocs();
