/**
 * Generate sidebar từ _category.json và _articles.json (3 cấp như Roblox: Category → Topic → Articles).
 * Script đọc: category → subdirs (topics) → .md trong mỗi topic.
 *
 * Tên hiển thị (label):
 *   - Category/Topic: lấy từ _category_.json (field "label"), không có thì dùng tên folder đã format.
 *   - Đổi tên hiển thị: sửa "label" trong _category_.json → chạy lại generate-sidebar → sidebar & breadcrumb đổi theo.
 *
 * Sort: _category.json (category/topic) và _articles.json (article) — field "sort", số nhỏ lên trước.
 * Active: _category.json (category/topic) và _articles.json (article) — "active": false thì bị ẩn khỏi sidebar.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DOCS = path.join(ROOT, 'docs');
const SIDEBARS_PATH = path.join(ROOT, 'sidebars.autogenerated.js');

const CATEGORY_META = '_category.json';
const CATEGORY_LABEL = '_category_.json';
const ARTICLES_FILE = '_articles.json';

function getMdFiles(dirPath) {
  if (!fs.existsSync(dirPath)) return [];
  return fs
    .readdirSync(dirPath, { withFileTypes: true })
    .filter(
      (e) =>
        e.isFile() &&
        (e.name.endsWith('.md') || e.name.endsWith('.mdx')) &&
        !e.name.startsWith('_')
    )
    .map((e) => e.name);
}

function getSubdirs(dirPath) {
  if (!fs.existsSync(dirPath)) return [];
  return fs
    .readdirSync(dirPath, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith('.'))
    .map((e) => e.name);
}

function getIdFromFilename(name) {
  return name.replace(/\.(md|mdx)$/i, '');
}

/** Đọc slug từ frontmatter (nếu có) để khớp _articles.json và Docusaurus doc id. */
function getSlugFromMdFile(sectionPath, filename) {
  const filePath = path.join(sectionPath, filename);
  if (!fs.existsSync(filePath)) return getIdFromFilename(filename);
  try {
    const raw = fs.readFileSync(filePath, 'utf8');
    const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (!match) return getIdFromFilename(filename);
    const fm = match[1];
    const slugMatch = fm.match(/^slug:\s*['"]?([^'"\r\n]+)['"]?\s*$/m) || fm.match(/^slug:\s*(.+)$/m);
    if (slugMatch && slugMatch[1]) return slugMatch[1].trim();
  } catch (_) {}
  return getIdFromFilename(filename);
}

function readCategoryMeta(dirPath) {
  const filePath = path.join(dirPath, CATEGORY_META);
  if (fs.existsSync(filePath)) {
    try {
      const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      return {
        active: typeof data.active === 'boolean' ? data.active : true,
        sort: typeof data.sort === 'number' ? data.sort : 999,
      };
    } catch {
      return { active: true, sort: 999 };
    }
  }
  return { active: true, sort: 999 };
}

function readCategoryLabel(dirPath, fallbackName, sidebarKey) {
  const filePath = path.join(dirPath, CATEGORY_LABEL);
  if (fs.existsSync(filePath)) {
    try {
      const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      const label = data.label || fallbackName;
      const link = data.link && typeof data.link === 'object' ? data.link : null;
      const key = typeof data.key === 'string' && data.key.trim() ? data.key.trim() : sidebarKey;
      return { label, link, key };
    } catch {
      //
    }
  }
  const label = fallbackName
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');
  return { label, link: null, key: sidebarKey };
}

function readArticlesJson(dirPath) {
  const filePath = path.join(dirPath, ARTICLES_FILE);
  if (fs.existsSync(filePath)) {
    try {
      const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      return Array.isArray(data) ? data : [];
    } catch {
      return [];
    }
  }
  return [];
}

/** Bài viết: id = tên file (khớp Docusaurus doc id). Sort/active tra _articles.json bằng slug frontmatter hoặc tên file. */
function buildArticleList(dirPath, articleMap) {
  const mdFiles = getMdFiles(dirPath);
  const activeArticles = [];
  for (const mdFile of mdFiles) {
    const id = getIdFromFilename(mdFile);
    const canonicalSlug = getSlugFromMdFile(dirPath, mdFile);
    const article = articleMap.get(canonicalSlug) || articleMap.get(canonicalSlug.toLowerCase()) || articleMap.get(id) || articleMap.get(id.toLowerCase());
    if (article && article.active === false) continue;
    activeArticles.push({
      id,
      filename: mdFile,
      sort: article && typeof article.sort === 'number' ? article.sort : 999,
    });
  }
  activeArticles.sort((a, b) => a.sort - b.sort);
  return activeArticles;
}

function generateSidebar() {
  if (!fs.existsSync(DOCS)) {
    console.log('[generate-sidebar] No docs/ folder, skip.');
    return;
  }

  const categories = [];
  const entries = fs.readdirSync(DOCS, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name.startsWith('.')) continue;

    const catPath = path.join(DOCS, entry.name);
    const categoryMeta = readCategoryMeta(catPath);
    if (!categoryMeta.active) continue;

    const subdirs = getSubdirs(catPath);
    const rootMdFiles = getMdFiles(catPath);

    // 3 cấp: category có topic (subdir) → topic → articles
    if (subdirs.length > 0) {
      const topicItems = [];
      const topicDirs = [];
      for (const topicName of subdirs) {
        const topicPath = path.join(catPath, topicName);
        const topicMeta = readCategoryMeta(topicPath);
        if (!topicMeta.active) continue;
        const mdFiles = getMdFiles(topicPath);
        if (mdFiles.length === 0) continue;

        const articlesJson = readArticlesJson(topicPath);
        const articleMap = new Map();
        for (const item of articlesJson) {
          if (item.id) {
            articleMap.set(item.id, item);
            articleMap.set(item.id.toLowerCase(), item);
          }
        }
        const activeArticles = buildArticleList(topicPath, articleMap);
        const docIds = activeArticles.map((a) => `${entry.name}/${topicName}/${a.id}`);

        const topicSidebarKey = `${entry.name}-${topicName}`;
        const topicSlugFull = `${entry.name}/${topicName}`;
        const { label: topicLabel, link: topicLink, key: topicKey } = readCategoryLabel(topicPath, topicName, topicSidebarKey);
        const topicItem = {
          type: 'category',
          label: topicLabel,
          items: docIds,
          collapsed: false,
          key: topicKey,
          link: {
            type: 'generated-index',
            title: topicLink?.title ?? topicLabel,
            slug: topicSlugFull,
            description: topicLink?.description ?? `Articles in ${topicLabel}`,
          },
        };
        topicItems.push({ sort: topicMeta.sort, item: topicItem });
        topicDirs.push(topicName);
      }
      topicItems.sort((a, b) => a.sort - b.sort);
      if (topicItems.length > 1) {
        const topicOrderLog = topicItems.map((t) => t.item.label + '(sort=' + t.sort + ')').join(' → ');
        console.log('[generate-sidebar] Thứ tự topic trong', entry.name + ':', topicOrderLog);
      }
      const topicSidebarItems = topicItems.map((t) => t.item);

      const { label: catLabel, link: catLink, key: catKey } = readCategoryLabel(catPath, entry.name, entry.name);
      const catSidebarItem = {
        type: 'category',
        label: catLabel,
        items: topicSidebarItems,
        collapsed: false,
        key: catKey,
        link: catLink || {
          type: 'generated-index',
          title: catLabel,
          slug: entry.name,
          description: `Articles in ${catLabel}`,
        },
      };
      categories.push({ sort: categoryMeta.sort, item: catSidebarItem });
      continue;
    }

    // 2 cấp (backward compat): category → articles ngay tại root
    if (rootMdFiles.length > 0) {
      const articlesJson = readArticlesJson(catPath);
      const articleMap = new Map();
      for (const item of articlesJson) {
        if (item.id) {
          articleMap.set(item.id, item);
          articleMap.set(item.id.toLowerCase(), item);
        }
      }
      const activeArticles = buildArticleList(catPath, articleMap);
      const items = activeArticles.map((a) => `${entry.name}/${a.id}`);
      const { label: catLabel, link: catLink, key: catKey } = readCategoryLabel(catPath, entry.name, entry.name);
      const catSidebarItem = {
        type: 'category',
        label: catLabel,
        items,
        collapsed: false,
        key: catKey,
        link: catLink || {
          type: 'generated-index',
          title: catLabel,
          slug: entry.name,
          description: `Articles in ${catLabel}`,
        },
      };
      categories.push({ sort: categoryMeta.sort, item: catSidebarItem });
    }
  }

  categories.sort((a, b) => a.sort - b.sort);
  const sidebarItems = categories.map((c) => c.item);

  if (categories.length > 0) {
    const orderLog = categories.map((c) => c.item.label + '(sort=' + c.sort + ')').join(' → ');
    console.log('[generate-sidebar] Thứ tự category:', orderLog);
  }

  const sidebarConfig = `// Sidebars: generated từ _category.json và _articles.json (3 cấp: Category → Topic → Articles)
// Sửa active/sort trong các file JSON → chạy yarn generate-sidebar (hoặc yarn dev tự chạy)
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: ${JSON.stringify(sidebarItems, null, 2)},
};
module.exports = sidebars;
// touched ${Date.now()}
`;

  try {
    fs.writeFileSync(SIDEBARS_PATH, sidebarConfig, 'utf8');
    let totalArticles = 0;
    for (const cat of sidebarItems) {
      if (!cat.items) continue;
      for (const i of cat.items) {
        if (typeof i === 'string') totalArticles++;
        else if (i.items) totalArticles += i.items.length;
      }
    }
    console.log('[generate-sidebar] Generated', path.relative(ROOT, SIDEBARS_PATH));
    console.log(`[generate-sidebar] Found ${sidebarItems.length} categories, ${totalArticles} articles (3-level: Category → Topic → Articles)`);
  } catch (error) {
    console.error('[generate-sidebar] Error writing sidebar file:', error.message);
    process.exit(1);
  }
}

generateSidebar();
